#!/bin/bash
# Deploy EAN Extraction infrastructure to Azure
# Usage: ./deploy.sh <environment> <location>
# Example: ./deploy.sh dev eastus

set -e

ENVIRONMENT=${1:-dev}
LOCATION=${2:-eastus}
RESOURCE_GROUP="rg-ean-extraction-${ENVIRONMENT}"
BASE_NAME="eanextract"

echo "🚀 Deploying EAN Extraction System"
echo "   Environment: ${ENVIRONMENT}"
echo "   Location: ${LOCATION}"
echo "   Resource Group: ${RESOURCE_GROUP}"
echo ""

# Check if logged in
if ! az account show &> /dev/null; then
    echo "❌ Not logged in to Azure. Please run 'az login' first."
    exit 1
fi

# Create resource group if it doesn't exist
echo "📦 Creating resource group..."
az group create --name "${RESOURCE_GROUP}" --location "${LOCATION}" --output none

# Prompt for secrets
echo ""
echo "🔐 Enter secrets for Key Vault:"
read -sp "MongoDB Connection String: " MONGODB_URI
echo ""
read -sp "Gemini API Key: " GEMINI_KEY
echo ""

# Deploy Bicep template
echo ""
echo "🏗️ Deploying infrastructure..."
DEPLOYMENT_OUTPUT=$(az deployment group create \
    --resource-group "${RESOURCE_GROUP}" \
    --template-file "$(dirname "$0")/../bicep/main.bicep" \
    --parameters \
        environment="${ENVIRONMENT}" \
        location="${LOCATION}" \
        baseName="${BASE_NAME}" \
        mongoDbConnectionString="${MONGODB_URI}" \
        geminiApiKey="${GEMINI_KEY}" \
    --query "properties.outputs" \
    --output json)

echo ""
echo "✅ Deployment complete!"
echo ""
echo "📋 Outputs:"
echo "${DEPLOYMENT_OUTPUT}" | jq -r 'to_entries[] | "   \(.key): \(.value.value)"'

# Generate .env file
STORAGE_ACCOUNT=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.storageAccountName.value')
STORAGE_BLOB_ENDPOINT=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.storageBlobEndpoint.value')
KEYVAULT_URI=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.keyVaultUri.value')
APPINSIGHTS_KEY=$(echo "${DEPLOYMENT_OUTPUT}" | jq -r '.appInsightsInstrumentationKey.value')

echo ""
echo "📝 Generating .env.${ENVIRONMENT} file..."

cat > "$(dirname "$0")/../../.env.${ENVIRONMENT}" << EOF
# Auto-generated by deploy.sh on $(date)
# Environment: ${ENVIRONMENT}

ENVIRONMENT=${ENVIRONMENT}

# Azure Storage
AZURE_STORAGE_ACCOUNT_URL=${STORAGE_BLOB_ENDPOINT}
AZURE_STORAGE_CONTAINER=product-images

# Azure Key Vault
AZURE_KEYVAULT_URL=${KEYVAULT_URI}

# MongoDB (retrieve from Key Vault or set manually)
# MONGODB_URI=<from-keyvault>
MONGODB_DATABASE=ean-extraction-${ENVIRONMENT}

# Gemini (retrieve from Key Vault or set manually)
# GEMINI_API_KEY=<from-keyvault>

# Application Insights
APPLICATIONINSIGHTS_INSTRUMENTATION_KEY=${APPINSIGHTS_KEY}

# Logging
LOG_LEVEL=INFO
LOG_FORMAT=json
EOF

echo "✅ Created .env.${ENVIRONMENT}"
echo ""
echo "🎉 Done! Next steps:"
echo "   1. Copy .env.${ENVIRONMENT} to .env"
echo "   2. Set MONGODB_URI and GEMINI_API_KEY (or use Key Vault references)"
echo "   3. Run 'poetry install' to install dependencies"
echo "   4. Run 'poetry run python -m src.db.init_indexes' to initialize database"
